image: golang:1.12

variables:
  GOFLAGS: -mod=readonly
  GOPATH: ${CI_PROJECT_DIR}/vendor/go
  # PKG_CONFIG_PATH: ${CI_PROJECT_DIR}/libgit2/lib/pkgconfig

.modcache: &modcache
  key: modcache
  paths:
    - vendor/go/pkg/mod/

before_script:
  - apt-get -qq update
  - apt-get install -y libssh2-1-dev cmake libssl-dev zlib1g-dev libcurl4-openssl-dev

stages:
  - dependencies
  - test
  - build

dependencies:
  stage: dependencies
  before_script:
    - apt-get -qq update
    - apt-get install -y libssh2-1-dev cmake libssl-dev zlib1g-dev libcurl4-openssl-dev
  script:
    - go mod download
    - pushd $GOPATH && go get -v -d github.com/libgit2/git2go && popd
    - pushd "${GOPATH}/src/github.com/libgit2/git2go"
    - git submodule update --init
    - make install-static
    - popd
  cache: *modcache

test:
  stage: test
  cache:
    <<: *modcache
    policy: pull
  script: go test ./...

build:
  stage: build
  cache:
    <<: *modcache
    policy: pull
  script: go build
  artifacts:
    paths:
    - beer
    expire_in: 1 week

