before:
  hooks:
    - go mod download
builds:
  - id: darwin-amd64
    env:
      # - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      # - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CGO_LDFLAGS=-framework CoreFoundation -framework Security
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/kunickiaj/beer/cmd.version={{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
  - id: linux-amd64
    env:
      - CC=gcc
      - CXX=g++
      - CGO_FLAGS=--sysroot=/sysroot/linux/amd64
      - CGO_LDFLAGS=--sysroot=/sysroot/linux/amd64
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/amd64
      - PKG_CONFIG_PATH=/sysroot/linux/amd64/usr/lib/x86_64-linux-gnu/pkgconfig:/sysroot/linux/amd64/usr/lib/pkgconfig:/sysroot/linux/amd64/usr/local/lib/pkgconfig
    ldflags:
      - -s -w -X github.com/kunickiaj/beer/cmd.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
archives:
  - id: dist
    builds:
      - darwin-amd64
      - linux-amd64
    replacements:
      linux: Linux
      amd64: x86_64
brews:
  - name: beer
    # Repository to push the tap to.
    tap:
      owner: kunickiaj
      name: homebrew-beer

    url_template: 'https://github.com/kunickiaj/beer/releases/download/{{ .Tag }}/{{ .ArtifactName }}'

    commit_author:
      name: goreleaserbot
      email: kunickiaj@gmail.com

    folder: Formula

    homepage: 'https://github.com/kunickiaj/beer'
    description: 'CLI for managing your JIRA / Gerrit / git workflow.'

    skip_upload: auto

    test: |
      system "#{bin}/beer --help"

    install: |
      bin.install "beer"
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - linux-amd64
    image_templates:
      - 'ghcr.io/kunickiaj/beer:{{ .Tag }}'
      - 'ghcr.io/kunickiaj/beer:latest'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
