version: 2

before:
  hooks:
    - go mod download
builds:
  - id: darwin-amd64
    env:
      - CGO_LDFLAGS=-framework CoreFoundation -framework Security
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/kunickiaj/beer/cmd.version={{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
  - id: darwin-arm64
    env:
      - CGO_LDFLAGS=-framework CoreFoundation -framework Security
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/kunickiaj/beer/cmd.version={{.Version}}
    goos:
      - darwin
    goarch:
      - arm64
  - id: linux-amd64
    env:
      - CC=gcc
      - CXX=g++
      - CGO_FLAGS=--sysroot=/sysroot/linux/amd64
      - CGO_LDFLAGS=--sysroot=/sysroot/linux/amd64
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/amd64
      - PKG_CONFIG_PATH=/sysroot/linux/amd64/usr/lib/x86_64-linux-gnu/pkgconfig:/sysroot/linux/amd64/usr/lib/pkgconfig:/sysroot/linux/amd64/usr/local/lib/pkgconfig
    ldflags:
      - -s -w -X github.com/kunickiaj/beer/cmd.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
archives:
  - id: dist
    ids:
      - darwin-amd64
      - darwin-arm64
      - linux-amd64
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
homebrew_casks:
  - name: beer
    # Repository to push the tap to.
    repository:
      owner: kunickiaj
      name: homebrew-beer

    url:
      template: 'https://github.com/kunickiaj/beer/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
      verified: 'github.com/kunickiaj/beer'

    commit_author:
      name: goreleaserbot
      email: kunickiaj@gmail.com

    homepage: 'https://github.com/kunickiaj/beer'
    description: 'CLI for managing your JIRA / Gerrit / git workflow.'

    skip_upload: auto

    hooks:
      post:
        install: |
          system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/beer"]

    caveats: |
      If macOS blocks execution, run:
        xattr -dr com.apple.quarantine $(which beer)

    binary: beer
dockers_v2:
  - ids:
      - linux-amd64
    images:
      - 'ghcr.io/kunickiaj/beer'
    tags:
      - '{{ .Tag }}'
      - latest
    platforms:
      - linux/amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: '{{ .Version }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
